#!/usr/bin/env python3
"""
สร้างไฟล์ C header จาก thai_words_filtered.txt สำหรับฝังเข้า flash
ใช้ run ครั้งเดียว (ไม่ใช่ pre-build script) เพราะพจนานุกรมไม่เปลี่ยนบ่อย
เหมือนไฟล์ generated/hyph-*.trie.h อื่นๆ ในโปรเจกต์

วิธีรัน (ที่ root ของ repo):
    python3 gen_thai_words_header.py

สร้างไฟล์: lib/Epub/Epub/hyphenation/generated/thai_words.h
"""

import os

SRC = "lib/Epub/Epub/hyphenation/thai_words_filtered.txt"
DST_DIR = "lib/Epub/Epub/hyphenation/generated"
DST = os.path.join(DST_DIR, "thai_words.h")


def escape_c_string(s: str) -> str:
    """Escape a string for embedding as a C string literal (UTF-8 bytes)."""
    out = []
    for byte in s.encode("utf-8"):
        out.append(f"\\x{byte:02x}")
    return "".join(out)


def main():
    with open(SRC, encoding="utf-8") as f:
        words = [line.strip() for line in f if line.strip()]

    words.sort()  # ensure UTF-8 byte order (matches codepoint order) for binary search

    os.makedirs(DST_DIR, exist_ok=True)

    offsets = [0]
    blob_escaped_parts = []
    current_offset = 0
    for w in words:
        encoded = w.encode("utf-8")
        blob_escaped_parts.append(escape_c_string(w))
        current_offset += len(encoded) + 1  # +1 for the \0 separator
        offsets.append(current_offset)

    blob_literal = "\\0".join(blob_escaped_parts) + "\\0"

    with open(DST, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by gen_thai_words_header.py - do not edit by hand.\n")
        f.write("// Source word list: PyThaiNLP words_th.txt (CC0-1.0 Public Domain)\n")
        f.write("// https://github.com/PyThaiNLP/pythainlp\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace ThaiWords {\n\n")
        f.write(f"constexpr size_t kThaiWordCount = {len(words)};\n\n")
        f.write("// All words concatenated, each terminated by \\0, sorted by UTF-8 byte order.\n")
        f.write("static const char kThaiWordsBlob[] =\n")
        # Split into chunks to avoid absurdly long single lines (some compilers/editors choke)
        chunk_size = 200
        for i in range(0, len(blob_literal), chunk_size):
            f.write(f'    "{blob_literal[i:i+chunk_size]}"\n')
        f.write(";\n\n")
        f.write("// Byte offset of each word within kThaiWordsBlob. kThaiWordCount+1 entries\n")
        f.write("// (last entry is the offset just past the final word's terminator).\n")
        f.write("static const uint32_t kThaiWordOffsets[] = {\n")
        for i in range(0, len(offsets), 16):
            row = ", ".join(str(o) for o in offsets[i:i+16])
            f.write(f"    {row},\n")
        f.write("};\n\n")
        f.write("}  // namespace ThaiWords\n")

    blob_bytes = sum(len(w.encode("utf-8")) + 1 for w in words)
    offset_bytes = len(offsets) * 4
    print(f"เขียนไฟล์: {DST}")
    print(f"จำนวนคำ: {len(words)}")
    print(f"ขนาดโดยประมาณ: {(blob_bytes + offset_bytes) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
